default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [--assume-in-merge]

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-fmt
        args: [-w]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']

  - repo: local
    hooks:
      - id: mypy
        name: Static type check with mypy
        entry: uv run mypy
        language: system
        pass_filenames: false
        types_or: [python, pyi]
      - id: pytest
        name: Test with pytest
        entry: uv run pytest tests
        language: system
        pass_filenames: false
        always_run: true
      - id: uv-lock
        name: Update uv lockfile
        entry: uv lock
        language: system
        pass_filenames: false
        files: ^(uv\.lock|pyproject\.toml)$
      - id: ruff-check
        name: Check Python code with Ruff
        entry: uv run ruff check --force-exclude --fix
        language: system
        require_serial: true
        types_or: [python, pyi]
      - id: ruff-format
        name: Format Python code with Ruff
        entry: uv run ruff format --force-exclude
        language: system
        require_serial: true
        types_or: [python, pyi]
