# DO NOT EDIT
# This file is automatically generated with copier using https://codeberg.org/slidge/legacy-module-template

# Builder
# *******
FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim AS builder

# install git for setuptools scm
RUN apt-get update -y && \
    apt-get install \
        git \
        make \
        build-essential \
        ca-certificates \
        cargo \
        curl \
        git \
        gcc \
        golang \
        g++ \
        libffi-dev \
        libssl-dev \
        pkg-config \
        python3-dev \
        libmupdf-dev \
        libgumbo-dev \
        libfreetype6-dev \
        libharfbuzz-dev \
        libjbig2dec0-dev \
        libjpeg62-turbo-dev \
        libmujs-dev \
        libopenjp2-7-dev \
        rustc \
        -y --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /build
ENV UV_PROJECT_ENVIRONMENT=/venv
ENV PATH="/venv/bin:/root/.cargo/bin:$PATH"
RUN uv venv $UV_PROJECT_ENVIRONMENT
COPY pyproject.toml uv.lock build.py README.md .
COPY slidge_whatsapp slidge_whatsapp
ARG SLIDGE_USE_LOCKFILE=
RUN [ -z "$SLIDGE_USE_LOCKFILE" ] && rm uv.lock || true
# install dependencies in /venv
# .git/ needs to be mounted for setuptools-scm to set the version
RUN --mount=source=.git,target=/build/.git,type=bind \
    uv sync --no-dev
ARG SLIDGE_PRERELEASE
RUN [ ! -z "$SLIDGE_PRERELEASE" ] && uv pip install slidge --upgrade --prerelease allow || true

# CI container
# ************
FROM builder AS ci

# We won't use this venv in CI, but this populates the uv cache in the container,
# minimizing (or even nulling) downloads.
RUN --mount=source=.git,target=/build/.git,type=bind \
    uv sync --all-groups --no-install-project
ENV UV_PROJECT_ENVIRONMENT="/woodpecker/src/codeberg.org/slidge/slidge-whatsapp/.venv"
ENV UV_LINK_MODE=copy
ENV PATH="$UV_PROJECT_ENVIRONMENT/bin:$PATH"

# Dev container
# *************
FROM builder AS dev

# copy "localhost" certs from the prosody slidge dev container, so
COPY --from=codeberg.org/slidge/prosody-slidge-dev:latest \
  /etc/prosody/certs/localhost.crt \
  /usr/local/share/ca-certificates/
RUN update-ca-certificates
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        libmagic1 \
        media-types \
        shared-mime-info \
        ffmpeg \
    && rm -rf /var/lib/apt/lists/*
ENV GOBIN="/usr/local/bin"
RUN go install -v github.com/go-python/gopy@master
RUN go install golang.org/x/tools/cmd/goimports@latest
RUN uv pip install watchdog[watchmedo]
COPY --from=ci /venv /venv
COPY ./watcher.py /build/
ENTRYPOINT ["python", "watcher.py", \
            "/venv/lib/python3.13/site-packages/slidge:/build/slidge_whatsapp", \
            "--dev-mode", "--debug", \
            "--legacy-module=slidge_whatsapp", "--jid=slidge.localhost", "--secret=secret"]


# Prod container
# **************
FROM docker.io/python:3.13-slim-trixie AS slidge-whatsapp

ENV PYTHONUNBUFFERED=1
ENV PATH="/venv/bin:$PATH"
STOPSIGNAL SIGINT
WORKDIR /var/lib/slidge
# libmagic1: to guess mime type from files
# libmupdf25.1: support for PDF file previews
# media-types: to determine file name suffix based on file type
# ffmpeg: incoming and outgoing media conversion
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        libmagic1 \
        libmupdf25.1 \
        media-types \
        shared-mime-info \
        ffmpeg \
    && rm -rf /var/lib/apt/lists/*
RUN addgroup --system --gid 10000 slidge
RUN adduser --system --uid 10000 --ingroup slidge --home /var/lib/slidge slidge
USER slidge
COPY --from=builder /venv /venv
COPY --from=builder /build/slidge_whatsapp /venv/lib/python3.13/site-packages/slidge_whatsapp
ENTRYPOINT ["slidge-whatsapp"]
