when:
  event: [ push, tag, pull_request ]
  path: [ "slidge_whatsapp/**/*.py", "docs/**/*", ".woodpecker/docs.yaml" ]

steps:
  build:
    image: codeberg.org/slidge/woodpecker-${CI_REPO_NAME}
    pull: true
    commands:
      # the first command updates the virtualenv, which is a no-op unless uv.lock has been modified
      - uv sync --frozen --all-groups --no-install-project
      - cd docs
      - make html

  publish:
    image: codeberg.org/slidge/woodpecker-publish-pages
    pull: true
    when:
      event: [ push, tag ]
    settings:
      token:
        from_secret: CODEBERG_TOKEN
