# It is way too CPU-expensive to run this on every push, especially building for arm64
# through buildkit, so we only run this on tagged releases.

when:
  branch: main
  event: tag

variables:
  - &image codeberg.org/slidge/woodpecker-${CI_REPO_NAME}

matrix:
  PYTHONVER:
    - "3.11"
    - "3.12"
    - "3.13"

steps:
  version:
    image: codeberg.org/slidge/woodpecker-version

  changelog:
    image: codeberg.org/slidge/woodpecker-generate-changelog
    pull: true

  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      build_args:
        PYTHONVER: "${PYTHONVER}"
      target: wheel
      output: ./dist-messy

  codeberg-pypi:
    when:
      event: [ push, tag ]
    image: *image
    environment:
      CODEBERG_TOKEN:
        from_secret: CODEBERG_TOKEN
    commands:
      - find ./dist-messy
      # A source dist is produced for each value of the matrix, but they have a different checksum,
      # which makes pypi upload fail, so we only copy the first one
      - mkdir ./dist/
      - if [ "$PYTHONVER" = "3.11" ]; then find ./dist-messy -type f -name "*.tar.gz" -exec cp {} dist/ \; ; fi
      - find ./dist-messy -type f -name "*.whl" -exec cp {} dist/ \;
      - uv publish --index codeberg --token $CODEBERG_TOKEN

  pypi:
    image: *image
    environment:
      PYPI_TOKEN:
        from_secret: PYPI_TOKEN
    commands:
      - uv publish --token $PYPI_TOKEN

  codeberg-release:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - dist/*
      api_key:
        from_secret: CODEBERG_TOKEN
      note: CHANGELOG
