when:
  event: [push, tag, pull_request]
  path: ["slidge_whatsapp/**/*", "pyproject.toml", "README.md"]

variables:
  - &only-main-tag
    when:
      branch: main
      event: tag

matrix:
  PYTHON_VERSION:
    - "3.11"
    - "3.12"
    - "3.13"
  ARCH:
    - amd64
    - arm64

labels:
  platform: linux/${ARCH}

steps:
  version:
    image: codeberg.org/slidge/woodpecker-version
    pull: true

  changelog:
    depends_on: version
    image: codeberg.org/slidge/woodpecker-generate-changelog
    pull: true

  build:
    image: codeberg.org/slidge/woodpecker-${CI_REPO_NAME}:${PYTHON_VERSION}-${ARCH}
    depends_on: version
    commands:
      - uv build

  codeberg-pypi-wheel:
    when:
      event: [push, tag]
    image: codeberg.org/slidge/woodpecker-${CI_REPO_NAME}:${PYTHON_VERSION}-${ARCH}
    pull: true
    depends_on: build
    environment:
      CODEBERG_TOKEN:
        from_secret: CODEBERG_TOKEN
    commands:
      - uv publish --index codeberg --token $CODEBERG_TOKEN dist/*.whl

  codeberg-pypi-sdist:
    when:
      event: [push, tag]
      matrix:
        PYTHON_VERSION: "3.11"
        ARCH: amd64
    image: codeberg.org/slidge/woodpecker-${CI_REPO_NAME}:${PYTHON_VERSION}-${ARCH}
    depends_on: build
    environment:
      CODEBERG_TOKEN:
        from_secret: CODEBERG_TOKEN
    commands:
      - uv publish --index codeberg --token $CODEBERG_TOKEN dist/*.tar.gz

  pypi-wheel:
    image: codeberg.org/slidge/woodpecker-${CI_REPO_NAME}:${PYTHON_VERSION}-${ARCH}
    depends_on: build
    <<: *only-main-tag
    environment:
      PYPI_TOKEN:
        from_secret: PYPI_TOKEN
    commands:
      - uv publish --token $PYPI_TOKEN dist/*.whl

  pypi-sdist:
    when:
      event: [tag]
      branch: main
      matrix:
        PYTHON_VERSION: "3.11"
        ARCH: amd64
    image: codeberg.org/slidge/woodpecker-${CI_REPO_NAME}:${PYTHON_VERSION}-${ARCH}
    depends_on: build
    environment:
      CODEBERG_TOKEN:
        from_secret: CODEBERG_TOKEN
    commands:
      - uv publish --token $PYPI_TOKEN dist/*.tar.gz

  codeberg-release:
    image: woodpeckerci/plugin-release
    depends_on: [changelog, build]
    <<: *only-main-tag
    settings:
      files:
        - dist/${CI_REPO_NAME}*
      api_key:
        from_secret: CODEBERG_TOKEN
      note: CHANGELOG
