when:
  event: [ push, pull_request ]
  path: [ "${CI_REPO_NAME}/**/*", "pyproject.toml", "uv.lock", "README.md" ]

variables:
  - &image codeberg.org/slidge/woodpecker-${CI_REPO_NAME}

steps:
  version:
    image: codeberg.org/slidge/woodpecker-version
    pull: true

  changelog:
    image: codeberg.org/slidge/woodpecker-generate-changelog
    pull: true

  build:
    image: *image
    commands: uv build

  codeberg-pypi:
    when:
      event: push
    image: *image
    environment:
      CODEBERG_TOKEN:
        from_secret: CODEBERG_TOKEN
    commands:
      - uv publish --index codeberg --token $CODEBERG_TOKEN
